/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Flux API
 * API para dados eleitorais e estatísticas de candidatos
 * OpenAPI spec version: 1.0
 */
import { apiInstance } from '../../../api-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getHealth = () => {
  /**
   * @summary Check API health
   */
  const healthControllerCheck = (
    options?: SecondParameter<typeof apiInstance<unknown>>
  ) => {
    return apiInstance<unknown>({ url: `/health`, method: 'GET' }, options);
  };
  return { healthControllerCheck };
};
export type HealthControllerCheckResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getHealth>['healthControllerCheck']>>
>;
