/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Flux API
 * API para dados eleitorais e estatísticas de candidatos
 * OpenAPI spec version: 1.0
 */
import { apiInstance } from '../../../../api-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getTenants = () => {
  const tenantsControllerFindAll = (
    options?: SecondParameter<typeof apiInstance<void>>
  ) => {
    return apiInstance<void>({ url: `/tenants`, method: 'GET' }, options);
  };
  return { tenantsControllerFindAll };
};
export type TenantsControllerFindAllResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTenants>['tenantsControllerFindAll']>>
>;
