/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Flux API
 * API para dados eleitorais e estatísticas de candidatos
 * OpenAPI spec version: 1.0
 */

export interface UpdateFlowDto {
  /** @minLength 1 */
  name?: string;
}
