/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Flux API
 * API para dados eleitorais e estatísticas de candidatos
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateFlowDto, UpdateFlowDto } from '../../../models';

import { apiInstance } from '../../../../api-instance';
import type { ErrorType, BodyType } from '../../../../api-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const flowsControllerCreate = (
  createFlowDto: BodyType<CreateFlowDto>,
  options?: SecondParameter<typeof apiInstance>,
  signal?: AbortSignal
) => {
  return apiInstance<void>(
    {
      url: `/flows`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createFlowDto,
      signal,
    },
    options
  );
};

export const getFlowsControllerCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof flowsControllerCreate>>,
    TError,
    { data: BodyType<CreateFlowDto> },
    TContext
  >;
  request?: SecondParameter<typeof apiInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof flowsControllerCreate>>,
  TError,
  { data: BodyType<CreateFlowDto> },
  TContext
> => {
  const mutationKey = ['flowsControllerCreate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof flowsControllerCreate>>,
    { data: BodyType<CreateFlowDto> }
  > = (props) => {
    const { data } = props ?? {};

    return flowsControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FlowsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof flowsControllerCreate>>
>;
export type FlowsControllerCreateMutationBody = BodyType<CreateFlowDto>;
export type FlowsControllerCreateMutationError = ErrorType<unknown>;

export const useFlowsControllerCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof flowsControllerCreate>>,
      TError,
      { data: BodyType<CreateFlowDto> },
      TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof flowsControllerCreate>>,
  TError,
  { data: BodyType<CreateFlowDto> },
  TContext
> => {
  return useMutation(
    getFlowsControllerCreateMutationOptions(options),
    queryClient
  );
};
export const flowsControllerFindAll = (
  options?: SecondParameter<typeof apiInstance>,
  signal?: AbortSignal
) => {
  return apiInstance<void>({ url: `/flows`, method: 'GET', signal }, options);
};

export const getFlowsControllerFindAllQueryKey = () => {
  return [`/flows`] as const;
};

export const getFlowsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof flowsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof flowsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof apiInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFlowsControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof flowsControllerFindAll>>
  > = ({ signal }) => flowsControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof flowsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FlowsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof flowsControllerFindAll>>
>;
export type FlowsControllerFindAllQueryError = ErrorType<unknown>;

export function useFlowsControllerFindAll<
  TData = Awaited<ReturnType<typeof flowsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof flowsControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof flowsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof flowsControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFlowsControllerFindAll<
  TData = Awaited<ReturnType<typeof flowsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof flowsControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof flowsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof flowsControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFlowsControllerFindAll<
  TData = Awaited<ReturnType<typeof flowsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof flowsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof apiInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFlowsControllerFindAll<
  TData = Awaited<ReturnType<typeof flowsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof flowsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof apiInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFlowsControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const invalidateFlowsControllerFindAll = async (
  queryClient: QueryClient,
  options?: InvalidateOptions
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getFlowsControllerFindAllQueryKey() },
    options
  );

  return queryClient;
};

export const flowsControllerFindOne = (
  id: string,
  options?: SecondParameter<typeof apiInstance>,
  signal?: AbortSignal
) => {
  return apiInstance<void>(
    { url: `/flows/${id}`, method: 'GET', signal },
    options
  );
};

export const getFlowsControllerFindOneQueryKey = (id: string) => {
  return [`/flows/${id}`] as const;
};

export const getFlowsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof flowsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof flowsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof apiInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFlowsControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof flowsControllerFindOne>>
  > = ({ signal }) => flowsControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof flowsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FlowsControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof flowsControllerFindOne>>
>;
export type FlowsControllerFindOneQueryError = ErrorType<unknown>;

export function useFlowsControllerFindOne<
  TData = Awaited<ReturnType<typeof flowsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof flowsControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof flowsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof flowsControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFlowsControllerFindOne<
  TData = Awaited<ReturnType<typeof flowsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof flowsControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof flowsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof flowsControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFlowsControllerFindOne<
  TData = Awaited<ReturnType<typeof flowsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof flowsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof apiInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFlowsControllerFindOne<
  TData = Awaited<ReturnType<typeof flowsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof flowsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof apiInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFlowsControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const invalidateFlowsControllerFindOne = async (
  queryClient: QueryClient,
  id: string,
  options?: InvalidateOptions
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getFlowsControllerFindOneQueryKey(id) },
    options
  );

  return queryClient;
};

export const flowsControllerUpdate = (
  id: string,
  updateFlowDto: BodyType<UpdateFlowDto>,
  options?: SecondParameter<typeof apiInstance>,
  signal?: AbortSignal
) => {
  return apiInstance<void>(
    {
      url: `/flows/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateFlowDto,
      signal,
    },
    options
  );
};

export const getFlowsControllerUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof flowsControllerUpdate>>,
    TError,
    { id: string; data: BodyType<UpdateFlowDto> },
    TContext
  >;
  request?: SecondParameter<typeof apiInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof flowsControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdateFlowDto> },
  TContext
> => {
  const mutationKey = ['flowsControllerUpdate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof flowsControllerUpdate>>,
    { id: string; data: BodyType<UpdateFlowDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return flowsControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FlowsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof flowsControllerUpdate>>
>;
export type FlowsControllerUpdateMutationBody = BodyType<UpdateFlowDto>;
export type FlowsControllerUpdateMutationError = ErrorType<unknown>;

export const useFlowsControllerUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof flowsControllerUpdate>>,
      TError,
      { id: string; data: BodyType<UpdateFlowDto> },
      TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof flowsControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdateFlowDto> },
  TContext
> => {
  return useMutation(
    getFlowsControllerUpdateMutationOptions(options),
    queryClient
  );
};
export const flowsControllerRemove = (
  id: string,
  options?: SecondParameter<typeof apiInstance>,
  signal?: AbortSignal
) => {
  return apiInstance<void>(
    { url: `/flows/${id}`, method: 'DELETE', signal },
    options
  );
};

export const getFlowsControllerRemoveMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof flowsControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof apiInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof flowsControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['flowsControllerRemove'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof flowsControllerRemove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return flowsControllerRemove(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FlowsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof flowsControllerRemove>>
>;

export type FlowsControllerRemoveMutationError = ErrorType<unknown>;

export const useFlowsControllerRemove = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof flowsControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof flowsControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getFlowsControllerRemoveMutationOptions(options),
    queryClient
  );
};
