/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Flux API
 * API para dados eleitorais e estatísticas de candidatos
 * OpenAPI spec version: 1.0
 */
import type { CreateFlowDto, UpdateFlowDto } from '../../models';

import { apiInstance } from '../../../api-instance';
import type { BodyType } from '../../../api-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getFlows = () => {
  const flowsControllerCreate = (
    createFlowDto: BodyType<CreateFlowDto>,
    options?: SecondParameter<typeof apiInstance<void>>
  ) => {
    return apiInstance<void>(
      {
        url: `/flows`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: createFlowDto,
      },
      options
    );
  };
  const flowsControllerFindAll = (
    options?: SecondParameter<typeof apiInstance<void>>
  ) => {
    return apiInstance<void>({ url: `/flows`, method: 'GET' }, options);
  };
  const flowsControllerFindOne = (
    id: string,
    options?: SecondParameter<typeof apiInstance<void>>
  ) => {
    return apiInstance<void>({ url: `/flows/${id}`, method: 'GET' }, options);
  };
  const flowsControllerUpdate = (
    id: string,
    updateFlowDto: BodyType<UpdateFlowDto>,
    options?: SecondParameter<typeof apiInstance<void>>
  ) => {
    return apiInstance<void>(
      {
        url: `/flows/${id}`,
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        data: updateFlowDto,
      },
      options
    );
  };
  const flowsControllerRemove = (
    id: string,
    options?: SecondParameter<typeof apiInstance<void>>
  ) => {
    return apiInstance<void>(
      { url: `/flows/${id}`, method: 'DELETE' },
      options
    );
  };
  return {
    flowsControllerCreate,
    flowsControllerFindAll,
    flowsControllerFindOne,
    flowsControllerUpdate,
    flowsControllerRemove,
  };
};
export type FlowsControllerCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFlows>['flowsControllerCreate']>>
>;
export type FlowsControllerFindAllResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFlows>['flowsControllerFindAll']>>
>;
export type FlowsControllerFindOneResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFlows>['flowsControllerFindOne']>>
>;
export type FlowsControllerUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFlows>['flowsControllerUpdate']>>
>;
export type FlowsControllerRemoveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFlows>['flowsControllerRemove']>>
>;
