/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Flux API
 * API para dados eleitorais e estatísticas de candidatos
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { apiInstance } from '../../../api-instance';
import type { ErrorType } from '../../../api-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const tenantsControllerFindAll = (
  options?: SecondParameter<typeof apiInstance>,
  signal?: AbortSignal
) => {
  return apiInstance<void>({ url: `/tenants`, method: 'GET', signal }, options);
};

export const getTenantsControllerFindAllQueryKey = () => {
  return [`/tenants`] as const;
};

export const getTenantsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof tenantsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof tenantsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof apiInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getTenantsControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof tenantsControllerFindAll>>
  > = ({ signal }) => tenantsControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof tenantsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TenantsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof tenantsControllerFindAll>>
>;
export type TenantsControllerFindAllQueryError = ErrorType<unknown>;

export function useTenantsControllerFindAll<
  TData = Awaited<ReturnType<typeof tenantsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tenantsControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tenantsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof tenantsControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTenantsControllerFindAll<
  TData = Awaited<ReturnType<typeof tenantsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tenantsControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tenantsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof tenantsControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTenantsControllerFindAll<
  TData = Awaited<ReturnType<typeof tenantsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tenantsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof apiInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useTenantsControllerFindAll<
  TData = Awaited<ReturnType<typeof tenantsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tenantsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof apiInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTenantsControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const invalidateTenantsControllerFindAll = async (
  queryClient: QueryClient,
  options?: InvalidateOptions
): Promise<QueryClient> => {
  await queryClient.invalidateQueries(
    { queryKey: getTenantsControllerFindAllQueryKey() },
    options
  );

  return queryClient;
};
