/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Flux API
 * API para dados eleitorais e estatísticas de candidatos
 * OpenAPI spec version: 1.0
 */
import { apiInstance } from '../../../../api-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getUsers = () => {
  const usersControllerFindAll = (
    options?: SecondParameter<typeof apiInstance<void>>
  ) => {
    return apiInstance<void>({ url: `/users`, method: 'GET' }, options);
  };
  return { usersControllerFindAll };
};
export type UsersControllerFindAllResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerFindAll']>>
>;
